fail_fast: true
default_stages: [commit]
repos:
  - repo : https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.(svg|json)
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
        files: .md
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.5
    hooks:
    - id: jupytext
      args: [--from, ipynb, --to, py, --pipe, black, --pipe-fmt, "ipynb", --show-changes, notebooks/*.ipynb]
      # https://jupytext.readthedocs.io/en/latest/using-pre-commit.html
      additional_dependencies:
        - black==22.3.0 # Matches hook

  - repo: https://github.com/psf/black
    rev: 23.1.0 # Change in jupytext hook too
    hooks:
    - id: black
      language_version: python3
